/**
 * ChromaMatrix Pro 鈥?Color Names Dictionaries & Closest Match Engine
 * Contains 140 English HTML Color Names and Traditional Chinese Colors (闆呯О)
 */
window.ColorNames = {
    english: [
        { name: "IndianRed", hex: "#CD5C5C" },
        { name: "LightCoral", hex: "#F08080" },
        { name: "Salmon", hex: "#FA8072" },
        { name: "DarkSalmon", hex: "#E9967A" },
        { name: "LightSalmon", hex: "#FFA07A" },
        { name: "Crimson", hex: "#DC143C" },
        { name: "Red", hex: "#FF0000" },
        { name: "FireBrick", hex: "#B22222" },
        { name: "DarkRed", hex: "#8B0000" },
        { name: "Pink", hex: "#FFC0CB" },
        { name: "LightPink", hex: "#FFB6C1" },
        { name: "HotPink", hex: "#FF69B4" },
        { name: "DeepPink", hex: "#FF1493" },
        { name: "MediumVioletRed", hex: "#C71585" },
        { name: "PaleVioletRed", hex: "#DB7093" },
        { name: "Coral", hex: "#FF7F50" },
        { name: "Tomato", hex: "#FF6347" },
        { name: "OrangeRed", hex: "#FF4500" },
        { name: "DarkOrange", hex: "#FF8C00" },
        { name: "Orange", hex: "#FFA500" },
        { name: "Gold", hex: "#FFD700" },
        { name: "Yellow", hex: "#FFFF00" },
        { name: "LightYellow", hex: "#FFFFE0" },
        { name: "LemonChiffon", hex: "#FFFACD" },
        { name: "LightGoldenrodYellow", hex: "#FAFAD2" },
        { name: "PapayaWhip", hex: "#FFEFD5" },
        { name: "Moccasin", hex: "#FFE4B5" },
        { name: "PeachPuff", hex: "#FFDAB9" },
        { name: "PaleGoldenrod", hex: "#EEE8AA" },
        { name: "Khaki", hex: "#F0E68C" },
        { name: "DarkKhaki", hex: "#BDB76B" },
        { name: "Lavender", hex: "#E6E6FA" },
        { name: "Thistle", hex: "#D8BFD8" },
        { name: "Plum", hex: "#DDA0DD" },
        { name: "Violet", hex: "#EE82EE" },
        { name: "Orchid", hex: "#DA70D6" },
        { name: "Fuchsia", hex: "#FF00FF" },
        { name: "Magenta", hex: "#FF00FF" },
        { name: "MediumOrchid", hex: "#BA55D3" },
        { name: "MediumPurple", hex: "#9370DB" },
        { name: "RebeccaPurple", hex: "#663399" },
        { name: "BlueViolet", hex: "#8A2BE2" },
        { name: "DarkViolet", hex: "#9400D3" },
        { name: "DarkOrchid", hex: "#9932CC" },
        { name: "DarkMagenta", hex: "#8B008B" },
        { name: "Purple", hex: "#800080" },
        { name: "Indigo", hex: "#4B0082" },
        { name: "SlateBlue", hex: "#6A5ACD" },
        { name: "DarkSlateBlue", hex: "#483D8B" },
        { name: "MediumSlateBlue", hex: "#7B68EE" },
        { name: "GreenYellow", hex: "#ADFF2F" },
        { name: "Chartreuse", hex: "#7FFF00" },
        { name: "LawnGreen", hex: "#7CFC00" },
        { name: "Lime", hex: "#00FF00" },
        { name: "LimeGreen", hex: "#32CD32" },
        { name: "PaleGreen", hex: "#98FB98" },
        { name: "LightGreen", hex: "#90EE90" },
        { name: "MediumSpringGreen", hex: "#00FA9A" },
        { name: "SpringGreen", hex: "#00FF7F" },
        { name: "MediumSeaGreen", hex: "#3CB371" },
        { name: "SeaGreen", hex: "#2E8B57" },
        { name: "ForestGreen", hex: "#228B22" },
        { name: "Green", hex: "#008000" },
        { name: "DarkGreen", hex: "#006400" },
        { name: "YellowGreen", hex: "#9ACD32" },
        { name: "OliveDrab", hex: "#6B8E23" },
        { name: "Olive", hex: "#808000" },
        { name: "DarkOliveGreen", hex: "#556B2F" },
        { name: "MediumAquamarine", hex: "#66CDAA" },
        { name: "DarkSeaGreen", hex: "#8FBC8B" },
        { name: "LightSeaGreen", hex: "#20B2AA" },
        { name: "DarkCyan", hex: "#008B8B" },
        { name: "Teal", hex: "#008080" },
        { name: "Aqua", hex: "#00FFFF" },
        { name: "Cyan", hex: "#00FFFF" },
        { name: "LightCyan", hex: "#E0FFFF" },
        { name: "PaleTurquoise", hex: "#AFEEEE" },
        { name: "Aquamarine", hex: "#7FFFD4" },
        { name: "Turquoise", hex: "#40E0D0" },
        { name: "MediumTurquoise", hex: "#48D1CC" },
        { name: "DarkTurquoise", hex: "#00CED1" },
        { name: "CadetBlue", hex: "#5F9EA0" },
        { name: "SteelBlue", hex: "#4682B4" },
        { name: "LightSteelBlue", hex: "#B0C4DE" },
        { name: "PowderBlue", hex: "#B0E0E6" },
        { name: "LightBlue", hex: "#ADD8E6" },
        { name: "SkyBlue", hex: "#87CEEB" },
        { name: "LightSkyBlue", hex: "#87CEFA" },
        { name: "DeepSkyBlue", hex: "#00BFFF" },
        { name: "DodgerBlue", hex: "#1E90FF" },
        { name: "CornflowerBlue", hex: "#6495ED" },
        { name: "RoyalBlue", hex: "#4169E1" },
        { name: "Blue", hex: "#0000FF" },
        { name: "MediumBlue", hex: "#0000CD" },
        { name: "DarkBlue", hex: "#00008B" },
        { name: "Navy", hex: "#000080" },
        { name: "MidnightBlue", hex: "#191970" },
        { name: "Cornsilk", hex: "#FFF8DC" },
        { name: "BlanchedAlmond", hex: "#FFEBCD" },
        { name: "Bisque", hex: "#FFE4C4" },
        { name: "NavajoWhite", hex: "#FFDEAD" },
        { name: "Wheat", hex: "#F5DEB3" },
        { name: "BurlyWood", hex: "#DEB887" },
        { name: "Tan", hex: "#D2B48C" },
        { name: "RosyBrown", hex: "#BC8F8F" },
        { name: "SandyBrown", hex: "#F4A460" },
        { name: "Goldenrod", hex: "#DAA520" },
        { name: "DarkGoldenrod", hex: "#B8860B" },
        { name: "Peru", hex: "#CD853F" },
        { name: "Chocolate", hex: "#D2691E" },
        { name: "SaddleBrown", hex: "#8B4513" },
        { name: "Sienna", hex: "#A0522D" },
        { name: "Brown", hex: "#A52A2A" },
        { name: "Maroon", hex: "#800000" },
        { name: "White", hex: "#FFFFFF" },
        { name: "Snow", hex: "#FFFAFA" },
        { name: "HoneyDew", hex: "#F0FFF0" },
        { name: "MintCream", hex: "#F5FFFA" },
        { name: "Azure", hex: "#F0FFFF" },
        { name: "AliceBlue", hex: "#F0F8FF" },
        { name: "GhostWhite", hex: "#F8F8FF" },
        { name: "WhiteSmoke", hex: "#F5F5F5" },
        { name: "SeaShell", hex: "#FFF5EE" },
        { name: "Beige", hex: "#F5F5DC" },
        { name: "OldLace", hex: "#FDF5E6" },
        { name: "FloralWhite", hex: "#FFFAF0" },
        { name: "Ivory", hex: "#FFFFF0" },
        { name: "AntiqueWhite", hex: "#FAEBD7" },
        { name: "Linen", hex: "#FAF0E6" },
        { name: "LavenderBlush", hex: "#FFF0F5" },
        { name: "MistyRose", hex: "#FFE4E1" },
        { name: "Gainsboro", hex: "#DCDCDC" },
        { name: "LightGray", hex: "#D3D3D3" },
        { name: "Silver", hex: "#C0C0C0" },
        { name: "DarkGray", hex: "#A9A9A9" },
        { name: "Gray", hex: "#808080" },
        { name: "DimGray", hex: "#696969" },
        { name: "LightSlateGray", hex: "#778899" },
        { name: "SlateGray", hex: "#708090" },
        { name: "DarkSlateGray", hex: "#2F4F4F" },
        { name: "Black", hex: "#000000" }
    ],
    chinese: [
        { name: "蔚蓝", hex: "#70F3FF" },
        { name: "蓝", hex: "#44CEF6" },
        { name: "碧蓝", hex: "#3EEDE7" },
        { name: "石青", hex: "#1685A9" },
        { name: "靛青", hex: "#177CB0" },
        { name: "靛蓝", hex: "#065279" },
        { name: "花青", hex: "#003472" },
        { name: "宝蓝", hex: "#4B5CC4" },
        { name: "蓝灰色", hex: "#A1AFC9" },
        { name: "藏青", hex: "#2E4E7E" },
        { name: "藏蓝", hex: "#3B2E7E" },
        { name: "黛", hex: "#4A4266" },
        { name: "黛绿", hex: "#426666" },
        { name: "黛蓝", hex: "#425066" },
        { name: "黛紫", hex: "#574266" },
        { name: "紫色", hex: "#8D4BBB" },
        { name: "紫酱", hex: "#815463" },
        { name: "酱紫", hex: "#815476" },
        { name: "紫檀", hex: "#4C221B" },
        { name: "绀青", hex: "#003371" },
        { name: "紫棠", hex: "#56004F" },
        { name: "青莲", hex: "#801DAE" },
        { name: "群青", hex: "#4C8DAE" },
        { name: "雪青", hex: "#B0A4E3" },
        { name: "丁香色", hex: "#CCA4E3" },
        { name: "藕色", hex: "#EDD1D8" },
        { name: "藕荷色", hex: "#E4C6D0" },
        { name: "朱砂", hex: "#FF461F" },
        { name: "火红", hex: "#FF2D51" },
        { name: "朱膘", hex: "#F36838" },
        { name: "妃色", hex: "#ED5736" },
        { name: "娇红", hex: "#FF4777" },
        { name: "品红", hex: "#F00056" },
        { name: "粉红", hex: "#FFB3A7" },
        { name: "桃红", hex: "#F47983" },
        { name: "海棠红", hex: "#DB5A6B" },
        { name: "樱桃色", hex: "#C93756" },
        { name: "酡颜", hex: "#F9906F" },
        { name: "银红", hex: "#F05654" },
        { name: "大红", hex: "#FF2121" },
        { name: "石榴红", hex: "#F20C00" },
        { name: "绛紫", hex: "#8C4356" },
        { name: "绯红", hex: "#C83C23" },
        { name: "胭脂", hex: "#9D2933" },
        { name: "朱红", hex: "#FF4C00" },
        { name: "丹", hex: "#FF4E20" },
        { name: "彤", hex: "#F35336" },
        { name: "酡红", hex: "#DC3023" },
        { name: "炎", hex: "#FF3300" },
        { name: "茜色", hex: "#CB3A56" },
        { name: "绾", hex: "#A98175" },
        { name: "檀", hex: "#B36D61" },
        { name: "嫣红", hex: "#EF7A82" },
        { name: "洋红", hex: "#FF0097" },
        { name: "枣红", hex: "#C32136" },
        { name: "殷红", hex: "#BE002F" },
        { name: "赫赤", hex: "#C91F37" },
        { name: "银朱", hex: "#BF242A" },
        { name: "赤", hex: "#C3272B" },
        { name: "栗色", hex: "#60281E" },
        { name: "玄色", hex: "#622A1D" },
        { name: "松花色", hex: "#BCE672" },
        { name: "柳黄", hex: "#C9DD22" },
        { name: "嫩绿", hex: "#BDDD22" },
        { name: "柳绿", hex: "#AFDD22" },
        { name: "葱黄", hex: "#A3D900" },
        { name: "葱绿", hex: "#9ED900" },
        { name: "豆绿", hex: "#9ED048" },
        { name: "豆青", hex: "#96CE54" },
        { name: "油绿", hex: "#00BC12" },
        { name: "葱倩", hex: "#0EB83A" },
        { name: "葱青", hex: "#0EB83A" },
        { name: "青葱", hex: "#0AA344" },
        { name: "石绿", hex: "#16A951" },
        { name: "松柏绿", hex: "#21A675" },
        { name: "松花绿", hex: "#057748" },
        { name: "绿沈", hex: "#0C8918" },
        { name: "绿色", hex: "#00E500" },
        { name: "草绿", hex: "#40DE5A" },
        { name: "青翠", hex: "#00E079" },
        { name: "青色", hex: "#00E09E" },
        { name: "翡翠色", hex: "#3DE1AD" },
        { name: "碧绿", hex: "#2ADD9C" },
        { name: "玉色", hex: "#2EDFA3" },
        { name: "缥", hex: "#7FECAD" },
        { name: "艾绿", hex: "#A4E2C6" },
        { name: "玉青", hex: "#7BCFA6" },
        { name: "碧色", hex: "#1BD1A5" },
        { name: "青碧", hex: "#48C0A3" },
        { name: "铜绿", hex: "#549688" },
        { name: "竹青", hex: "#789262" },
        { name: "墨灰", hex: "#758A99" },
        { name: "墨色", hex: "#50616D" },
        { name: "鸦青", hex: "#424C50" },
        { name: "黯", hex: "#41555D" },
        { name: "樱草色", hex: "#EAFF56" },
        { name: "鹅黄", hex: "#FFF143" },
        { name: "鸭黄", hex: "#FAFF72" },
        { name: "杏黄", hex: "#FFA631" },
        { name: "橙黄", hex: "#FFA400" },
        { name: "橙色", hex: "#FA8C35" },
        { name: "杏红", hex: "#FF8C31" },
        { name: "橘黄", hex: "#FF8936" },
        { name: "橘红", hex: "#FF7500" },
        { name: "藤黄", hex: "#FFB61E" },
        { name: "姜黄", hex: "#FFC773" },
        { name: "雌黄", hex: "#FFC64B" },
        { name: "赤金", hex: "#F2BE45" },
        { name: "缃色", hex: "#F0C239" },
        { name: "雄黄", hex: "#E9BB1D" },
        { name: "秋香色", hex: "#D9B611" },
        { name: "金色", hex: "#EACD76" },
        { name: "牙色", hex: "#EEDEB0" },
        { name: "枯黄", hex: "#D3B17D" },
        { name: "黄栌", hex: "#E29C45" },
        { name: "乌金", hex: "#A78E44" },
        { name: "昏黄", hex: "#C89B40" },
        { name: "棕黄", hex: "#AE7000" },
        { name: "琥珀", hex: "#CA6924" },
        { name: "棕色", hex: "#B25D25" },
        { name: "茶色", hex: "#B35C44" },
        { name: "棕红", hex: "#9B4400" },
        { name: "赭", hex: "#9C5333" },
        { name: "驼色", hex: "#A88462" },
        { name: "秋色", hex: "#896C39" },
        { name: "棕绿", hex: "#827100" },
        { name: "褐色", hex: "#6E511E" },
        { name: "棕黑", hex: "#7C4B00" },
        { name: "赭色", hex: "#955539" },
        { name: "赭石", hex: "#845A33" },
        { name: "精白", hex: "#FFFFFF" },
        { name: "银白", hex: "#E9E7EF" },
        { name: "铅白", hex: "#F0F0F4" },
        { name: "霜色", hex: "#E9F1F6" },
        { name: "雪白", hex: "#F0FCFF" },
        { name: "莹白", hex: "#E3F9FD" },
        { name: "月白", hex: "#D6ECF0" },
        { name: "象牙白", hex: "#FFFBF0" },
        { name: "缟", hex: "#F2ECDE" },
        { name: "鱼肚白", hex: "#FCEFE8" },
        { name: "白粉", hex: "#FFF2DF" },
        { name: "荼白", hex: "#F3F9F1" },
        { name: "鸭卵青", hex: "#E0EEE8" },
        { name: "素", hex: "#E0F0E9" },
        { name: "青白", hex: "#C0EBD7" },
        { name: "蟹壳青", hex: "#BBCDC5" },
        { name: "花白", hex: "#C2CCD0" },
        { name: "老银", hex: "#BACAC6" },
        { name: "灰色", hex: "#808080" },
        { name: "苍色", hex: "#75878A" },
        { name: "水色", hex: "#88ADA6" },
        { name: "黝", hex: "#6B6882" },
        { name: "乌色", hex: "#725E82" },
        { name: "玄青", hex: "#3D3B4F" },
        { name: "乌黑", hex: "#392F41" },
        { name: "黎", hex: "#75664D" },
        { name: "黧", hex: "#5D513C" },
        { name: "黝黑", hex: "#665757" },
        { name: "缁色", hex: "#493131" },
        { name: "煤黑", hex: "#312520" },
        { name: "漆黑", hex: "#161823" },
        { name: "黑色", hex: "#000000" }
    ],
    cache: new Map(),
    findClosest: function(targetHex) {
        if (!targetHex || !window.ColorMath) return { english: "Unknown", englishHex: "#000000", chinese: "\u672a\u77e5", chineseHex: "#000000" };
        targetHex = targetHex.toUpperCase();
        if (this.cache.has(targetHex)) {
            return this.cache.get(targetHex);
        }
        const { hexToRgb } = window.ColorMath;
        const targetRgb = hexToRgb(targetHex);
        if (!targetRgb) return { english: "Unknown", englishHex: "#000000", chinese: "\u672a\u77e5", chineseHex: "#000000" };
        
        const calcDistance = (rgb1, rgb2) => {
            const rMean = (rgb1.r + rgb2.r) / 2;
            const dr = rgb1.r - rgb2.r;
            const dg = rgb1.g - rgb2.g;
            const db = rgb1.b - rgb2.b;
            return (2 + rMean / 256) * dr * dr + 4 * dg * dg + (2 + (255 - rMean) / 256) * db * db;
        };

        let minEngDist = Infinity;
        let closestEng = null;
        for (let i = 0; i < this.english.length; i++) {
            const item = this.english[i];
            const rgb = hexToRgb(item.hex);
            if (!rgb) continue;
            const dist = calcDistance(targetRgb, rgb);
            if (dist < minEngDist) {
                minEngDist = dist;
                closestEng = item;
            }
        }

        let minChiDist = Infinity;
        let closestChi = null;
        for (let i = 0; i < this.chinese.length; i++) {
            const item = this.chinese[i];
            const rgb = hexToRgb(item.hex);
            if (!rgb) continue;
            const dist = calcDistance(targetRgb, rgb);
            if (dist < minChiDist) {
                minChiDist = dist;
                closestChi = item;
            }
        }

        const result = {
            english: closestEng ? closestEng.name : "Unknown",
            englishHex: closestEng ? closestEng.hex : "#000000",
            chinese: closestChi ? closestChi.name : "\u672a\u77e5",
            chineseHex: closestChi ? closestChi.hex : "#000000"
        };
        this.cache.set(targetHex, result);
        return result;
    }
};